name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode Solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: LeetCode
          verbose: true
          commit-header: "[LeetCode Sync]"
